# Generated by Django 4.2.2 on 2024-07-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_car_owner_moto_owner_alter_mileage_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='amount',
            field=models.IntegerField(default=1000, verbose_name='Цена'),
        ),
    ]
